package com.peseer.ops.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 *
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("daily_operation_record", "record_id", DailyOperationRecord.class);
		arp.addMapping("dynamic_cookie", "id", DynamicCookie.class);
		arp.addMapping("ent_qxb_seed_bak", EntQxbSeedBak.class);
		arp.addMapping("event_round_one", "id", EventRoundOne.class);
		arp.addMapping("event_round_two", "id", EventRoundTwo.class);
		arp.addMapping("ops_angel_user_info", "id", OpsAngelUserInfo.class);
		arp.addMapping("ops_category_biz", "id", OpsCategoryBiz.class);
		arp.addMapping("ops_category_domain", "id", OpsCategoryDomain.class);
		arp.addMapping("ops_category_media", "id", OpsCategoryMedia.class);
		arp.addMapping("ops_category_trader_report", "id", OpsCategoryTraderReport.class);
		arp.addMapping("ops_city_lnglat_info", OpsCityLnglatInfo.class);
		arp.addMapping("ops_exit_event_detail", "event_id", OpsExitEventDetail.class);
		arp.addMapping("ops_fund_entity", "id", OpsFundEntity.class);
		arp.addMapping("ops_fund_info", "fund_id", OpsFundInfo.class);
		arp.addMapping("ops_fund_lp_mapping", "id", OpsFundLpMapping.class);
		arp.addMapping("ops_hnwi_info", "id", OpsHnwiInfo.class);
		arp.addMapping("ops_invest_event_detail", "event_id", OpsInvestEventDetail.class);
		arp.addMapping("ops_lp_info", "lp_id", OpsLpInfo.class);
		arp.addMapping("ops_lp_member", "id", OpsLpMember.class);
		arp.addMapping("ops_monitor_media", "id", OpsMonitorMedia.class);
		arp.addMapping("ops_monitor_media_index", "id", OpsMonitorMediaIndex.class);
		arp.addMapping("ops_monitor_wechat", "id", OpsMonitorWechat.class);
		arp.addMapping("ops_org_extend_entity", "id", OpsOrgExtendEntity.class);
		arp.addMapping("ops_org_gp_info", "org_id", OpsOrgGpInfo.class);
		arp.addMapping("ops_org_lp_info", "org_id", OpsOrgLpInfo.class);
		arp.addMapping("ops_org_user_info", "id", OpsOrgUserInfo.class);
		arp.addMapping("ops_report_cv", OpsReportCv.class);
		arp.addMapping("ops_schedule", "id", OpsSchedule.class);
		arp.addMapping("ops_startups_info", "id", OpsStartupsInfo.class);
		arp.addMapping("ops_stat_inst_research", "id", OpsStatInstResearch.class);
		arp.addMapping("ops_stat_toe_ma", "id", OpsStatToeMa.class);
	}
}
