package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsStatInstResearch<M extends BaseOpsStatInstResearch<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_stat_inst_research";

	/**
	 * 自增Id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增Id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 机构全称
	 */
	public void setInstName(java.lang.String instName) {
		set("inst_name", instName);
	}

	/**
	 * 机构全称
	 */
	public java.lang.String getInstName() {
		return get("inst_name");
	}

	/**
	 * 机构类型
	 */
	public void setInstCat(java.lang.String instCat) {
		set("inst_cat", instCat);
	}

	/**
	 * 机构类型
	 */
	public java.lang.String getInstCat() {
		return get("inst_cat");
	}

	/**
	 * 调研日期
	 */
	public void setHappenDate(java.lang.String happenDate) {
		set("happen_date", happenDate);
	}

	/**
	 * 调研日期
	 */
	public java.lang.String getHappenDate() {
		return get("happen_date");
	}

	/**
	 * 调研对象代码
	 */
	public void setObjId(java.lang.String objId) {
		set("obj_id", objId);
	}

	/**
	 * 调研对象代码
	 */
	public java.lang.String getObjId() {
		return get("obj_id");
	}

	/**
	 * 调研对象名称
	 */
	public void setObjName(java.lang.String objName) {
		set("obj_name", objName);
	}

	/**
	 * 调研对象名称
	 */
	public java.lang.String getObjName() {
		return get("obj_name");
	}

	/**
	 * 调研方式
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 调研方式
	 */
	public java.lang.String getType() {
		return get("type");
	}

	/**
	 * 调研内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	/**
	 * 调研内容
	 */
	public java.lang.String getContent() {
		return get("content");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
