package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsMonitorMediaIndex<M extends BaseOpsMonitorMediaIndex<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_monitor_media_index";

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增主键
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 公众号/媒体的ID
	 */
	public void setRefId(java.lang.Integer refId) {
		set("ref_id", refId);
	}

	/**
	 * 公众号/媒体的ID
	 */
	public java.lang.Integer getRefId() {
		return get("ref_id");
	}

	/**
	 * 文章标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 文章标题
	 */
	public java.lang.String getTitle() {
		return get("title");
	}

	/**
	 * url
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	/**
	 * url
	 */
	public java.lang.String getUrl() {
		return get("url");
	}

	/**
	 * 1:媒体 2：微信
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 1:媒体 2：微信
	 */
	public java.lang.Integer getType() {
		return get("type");
	}

	/**
	 * ip地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	/**
	 * ip地址
	 */
	public java.lang.String getIp() {
		return get("ip");
	}

	/**
	 * 内容长度
	 */
	public void setLen(java.lang.Integer len) {
		set("len", len);
	}

	/**
	 * 内容长度
	 */
	public java.lang.Integer getLen() {
		return get("len");
	}

	/**
	 * 建立时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 建立时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
