package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDynamicCookie<M extends BaseDynamicCookie<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "dynamic_cookie";

	/**
	 * 
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 媒体标识
	 */
	public void setHost(java.lang.String host) {
		set("host", host);
	}

	/**
	 * 媒体标识
	 */
	public java.lang.String getHost() {
		return get("host");
	}

	/**
	 * COOKIE
	 */
	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}

	/**
	 * COOKIE
	 */
	public java.lang.String getCookie() {
		return get("cookie");
	}

	/**
	 * 帐号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	/**
	 * 帐号
	 */
	public java.lang.String getAccount() {
		return get("account");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return get("password");
	}

	/**
	 * 状态为1表示正常，其它表示异常
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	/**
	 * 状态为1表示正常，其它表示异常
	 */
	public java.lang.Integer getState() {
		return get("state");
	}

	/**
	 * 本COOKIE抓取失败次数
	 */
	public void setFailCount(java.lang.Integer failCount) {
		set("fail_count", failCount);
	}

	/**
	 * 本COOKIE抓取失败次数
	 */
	public java.lang.Integer getFailCount() {
		return get("fail_count");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
