package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsCategoryBiz<M extends BaseOpsCategoryBiz<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_category_biz";

	/**
	 * 自增Id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增Id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 基础分类ID
	 */
	public void setBizCatId(java.lang.Integer bizCatId) {
		set("biz_cat_id", bizCatId);
	}

	/**
	 * 基础分类ID
	 */
	public java.lang.Integer getBizCatId() {
		return get("biz_cat_id");
	}

	/**
	 * 基础分类名称
	 */
	public void setBizCatName(java.lang.String bizCatName) {
		set("biz_cat_name", bizCatName);
	}

	/**
	 * 基础分类名称
	 */
	public java.lang.String getBizCatName() {
		return get("biz_cat_name");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
