package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsCategoryTraderReport<M extends BaseOpsCategoryTraderReport<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_category_trader_report";

	/**
	 * 自增Id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增Id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 基础分类ID
	 */
	public void setBizCatId(java.lang.Integer bizCatId) {
		set("biz_cat_id", bizCatId);
	}

	/**
	 * 基础分类ID
	 */
	public java.lang.Integer getBizCatId() {
		return get("biz_cat_id");
	}

	/**
	 * 券商报告分类名称（别称，派生于基础分类名称）
	 */
	public void setTraderRptCatName(java.lang.String traderRptCatName) {
		set("trader_rpt_cat_name", traderRptCatName);
	}

	/**
	 * 券商报告分类名称（别称，派生于基础分类名称）
	 */
	public java.lang.String getTraderRptCatName() {
		return get("trader_rpt_cat_name");
	}

	/**
	 * 关联data_source数据库choice_report_type表中的type字段
	 */
	public void setOpsCateTraderRptid(java.lang.Integer opsCateTraderRptid) {
		set("ops_cate_trader_rptid", opsCateTraderRptid);
	}

	/**
	 * 关联data_source数据库choice_report_type表中的type字段
	 */
	public java.lang.Integer getOpsCateTraderRptid() {
		return get("ops_cate_trader_rptid");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
