package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsOrgLpInfo<M extends BaseOpsOrgLpInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_org_lp_info";

	/**
	 * 机构Id
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构Id
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 机构名称
	 */
	public void setOrgCnName(java.lang.String orgCnName) {
		set("org_cn_name", orgCnName);
	}

	/**
	 * 机构名称
	 */
	public java.lang.String getOrgCnName() {
		return get("org_cn_name");
	}

	/**
	 * 中文名简称
	 */
	public void setOrgCnShort(java.lang.String orgCnShort) {
		set("org_cn_short", orgCnShort);
	}

	/**
	 * 中文名简称
	 */
	public java.lang.String getOrgCnShort() {
		return get("org_cn_short");
	}

	/**
	 * 机构别名
	 */
	public void setOrgNickname(java.lang.String orgNickname) {
		set("org_nickname", orgNickname);
	}

	/**
	 * 机构别名
	 */
	public java.lang.String getOrgNickname() {
		return get("org_nickname");
	}

	/**
	 * 机构英文名称
	 */
	public void setOrgEnName(java.lang.String orgEnName) {
		set("org_en_name", orgEnName);
	}

	/**
	 * 机构英文名称
	 */
	public java.lang.String getOrgEnName() {
		return get("org_en_name");
	}

	/**
	 * RDD整理映射企业实体
	 */
	public void setOrgMapEntity(java.lang.String orgMapEntity) {
		set("org_map_entity", orgMapEntity);
	}

	/**
	 * RDD整理映射企业实体
	 */
	public java.lang.String getOrgMapEntity() {
		return get("org_map_entity");
	}

	/**
	 * 机构类型： 1.公共养老金；2.家族基金、大学及基金会；3.FOF；4.引导基金；5.资产管理公司；6.银行、保险、信托；7.主权财富基金
	 */
	public void setOrgType(java.lang.Integer orgType) {
		set("org_type", orgType);
	}

	/**
	 * 机构类型： 1.公共养老金；2.家族基金、大学及基金会；3.FOF；4.引导基金；5.资产管理公司；6.银行、保险、信托；7.主权财富基金
	 */
	public java.lang.Integer getOrgType() {
		return get("org_type");
	}

	/**
	 * 电话
	 */
	public void setOrgTel(java.lang.String orgTel) {
		set("org_tel", orgTel);
	}

	/**
	 * 电话
	 */
	public java.lang.String getOrgTel() {
		return get("org_tel");
	}

	/**
	 * 邮件
	 */
	public void setOrgMail(java.lang.String orgMail) {
		set("org_mail", orgMail);
	}

	/**
	 * 邮件
	 */
	public java.lang.String getOrgMail() {
		return get("org_mail");
	}

	/**
	 * 机构描述
	 */
	public void setOrgCnDesc(java.lang.String orgCnDesc) {
		set("org_cn_desc", orgCnDesc);
	}

	/**
	 * 机构描述
	 */
	public java.lang.String getOrgCnDesc() {
		return get("org_cn_desc");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
