package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntQxbSeedBak<M extends BaseEntQxbSeedBak<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_qxb_seed_bak";

	/**
	 * 企业名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getName() {
		return get("name");
	}

}
