package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsMonitorWechat<M extends BaseOpsMonitorWechat<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_monitor_wechat";

	/**
	 * 
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 微信公众号
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 微信公众号
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 微信号
	 */
	public void setWechatNo(java.lang.String wechatNo) {
		set("wechat_no", wechatNo);
	}

	/**
	 * 微信号
	 */
	public java.lang.String getWechatNo() {
		return get("wechat_no");
	}

	/**
	 * 配图
	 */
	public void setMatchPic(java.lang.String matchPic) {
		set("match_pic", matchPic);
	}

	/**
	 * 配图
	 */
	public java.lang.String getMatchPic() {
		return get("match_pic");
	}

	/**
	 * 公众号所属地区
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}

	/**
	 * 公众号所属地区
	 */
	public java.lang.String getArea() {
		return get("area");
	}

	/**
	 * 
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	/**
	 * 
	 */
	public java.lang.String getDescription() {
		return get("description");
	}

	/**
	 * 主体
	 */
	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	/**
	 * 主体
	 */
	public java.lang.String getSubject() {
		return get("subject");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 是否启用
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	/**
	 * 是否启用
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	/**
	 * 攫取异常信息
	 */
	public void setCrawleMessage(java.lang.String crawleMessage) {
		set("crawle_message", crawleMessage);
	}

	/**
	 * 攫取异常信息
	 */
	public java.lang.String getCrawleMessage() {
		return get("crawle_message");
	}

}
