package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsMonitorMedia<M extends BaseOpsMonitorMedia<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_monitor_media";

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增主键
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 监控分组
	 */
	public void setMonitorGroup(java.lang.String monitorGroup) {
		set("monitor_group", monitorGroup);
	}

	/**
	 * 监控分组
	 */
	public java.lang.String getMonitorGroup() {
		return get("monitor_group");
	}

	/**
	 * 媒体分组
	 */
	public void setMediaGroup(java.lang.String mediaGroup) {
		set("media_group", mediaGroup);
	}

	/**
	 * 媒体分组
	 */
	public java.lang.String getMediaGroup() {
		return get("media_group");
	}

	/**
	 * 监控名称
	 */
	public void setMonitorName(java.lang.String monitorName) {
		set("monitor_name", monitorName);
	}

	/**
	 * 监控名称
	 */
	public java.lang.String getMonitorName() {
		return get("monitor_name");
	}

	/**
	 * 数据来源URL
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	/**
	 * 数据来源URL
	 */
	public java.lang.String getUrl() {
		return get("url");
	}

	/**
	 * 代码的解析表达式,有可能是XPATH,jquery选择器
	 */
	public void setListExpression(java.lang.String listExpression) {
		set("list_expression", listExpression);
	}

	/**
	 * 代码的解析表达式,有可能是XPATH,jquery选择器
	 */
	public java.lang.String getListExpression() {
		return get("list_expression");
	}

	/**
	 * 标题的表达式
	 */
	public void setTitleExpression(java.lang.String titleExpression) {
		set("title_expression", titleExpression);
	}

	/**
	 * 标题的表达式
	 */
	public java.lang.String getTitleExpression() {
		return get("title_expression");
	}

	/**
	 * 媒体频道
	 */
	public void setMediaChannel(java.lang.String mediaChannel) {
		set("media_channel", mediaChannel);
	}

	/**
	 * 媒体频道
	 */
	public java.lang.String getMediaChannel() {
		return get("media_channel");
	}

	/**
	 * 监控频率
	 */
	public void setFrequency(java.lang.Integer frequency) {
		set("frequency", frequency);
	}

	/**
	 * 监控频率
	 */
	public java.lang.Integer getFrequency() {
		return get("frequency");
	}

	/**
	 * 地域
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}

	/**
	 * 地域
	 */
	public java.lang.String getArea() {
		return get("area");
	}

	/**
	 * 是否启用(1是启用,0是暂停监控)
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	/**
	 * 是否启用(1是启用,0是暂停监控)
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	/**
	 * 分页表达式
	 */
	public void setPageExpression(java.lang.String pageExpression) {
		set("page_expression", pageExpression);
	}

	/**
	 * 分页表达式
	 */
	public java.lang.String getPageExpression() {
		return get("page_expression");
	}

	/**
	 * tag的表达式
	 */
	public void setTagExpression(java.lang.String tagExpression) {
		set("tag_expression", tagExpression);
	}

	/**
	 * tag的表达式
	 */
	public java.lang.String getTagExpression() {
		return get("tag_expression");
	}

	/**
	 * url代表的TAG
	 */
	public void setUrlTag(java.lang.String urlTag) {
		set("url_tag", urlTag);
	}

	/**
	 * url代表的TAG
	 */
	public java.lang.String getUrlTag() {
		return get("url_tag");
	}

	/**
	 * 最多抓取到第几页
	 */
	public void setLimitPage(java.lang.Integer limitPage) {
		set("limit_page", limitPage);
	}

	/**
	 * 最多抓取到第几页
	 */
	public java.lang.Integer getLimitPage() {
		return get("limit_page");
	}

	/**
	 * 建立时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 建立时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 执行结果备注
	 */
	public void setResultNote(java.lang.String resultNote) {
		set("result_note", resultNote);
	}

	/**
	 * 执行结果备注
	 */
	public java.lang.String getResultNote() {
		return get("result_note");
	}

	/**
	 * 上次监控是否成功
	 */
	public void setIsSuccess(java.lang.Boolean isSuccess) {
		set("is_success", isSuccess);
	}

	/**
	 * 上次监控是否成功
	 */
	public java.lang.Boolean getIsSuccess() {
		return get("is_success");
	}

}
