package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsFundLpMapping<M extends BaseOpsFundLpMapping<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_fund_lp_mapping";

	/**
	 * 索引Id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 索引Id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 基金Id
	 */
	public void setFundId(java.lang.Integer fundId) {
		set("fund_id", fundId);
	}

	/**
	 * 基金Id
	 */
	public java.lang.Integer getFundId() {
		return get("fund_id");
	}

	/**
	 * 基金名称
	 */
	public void setFundName(java.lang.String fundName) {
		set("fund_name", fundName);
	}

	/**
	 * 基金名称
	 */
	public java.lang.String getFundName() {
		return get("fund_name");
	}

	/**
	 * 机构ID
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构ID
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 机构名称
	 */
	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	/**
	 * 机构名称
	 */
	public java.lang.String getOrgName() {
		return get("org_name");
	}

	/**
	 * 机构简称
	 */
	public void setOrgCnShort(java.lang.String orgCnShort) {
		set("org_cn_short", orgCnShort);
	}

	/**
	 * 机构简称
	 */
	public java.lang.String getOrgCnShort() {
		return get("org_cn_short");
	}

	/**
	 * LP的ID
	 */
	public void setLpId(java.lang.Integer lpId) {
		set("lp_id", lpId);
	}

	/**
	 * LP的ID
	 */
	public java.lang.Integer getLpId() {
		return get("lp_id");
	}

	/**
	 * LP的名称
	 */
	public void setLpName(java.lang.String lpName) {
		set("lp_name", lpName);
	}

	/**
	 * LP的名称
	 */
	public java.lang.String getLpName() {
		return get("lp_name");
	}

	/**
	 * LP对应的实体
	 */
	public void setLpEntity(java.lang.String lpEntity) {
		set("lp_entity", lpEntity);
	}

	/**
	 * LP对应的实体
	 */
	public java.lang.String getLpEntity() {
		return get("lp_entity");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
