package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDailyOperationRecord<M extends BaseDailyOperationRecord<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "daily_operation_record";

	/**
	 * record id
	 */
	public void setRecordId(java.lang.Integer recordId) {
		set("record_id", recordId);
	}

	/**
	 * record id
	 */
	public java.lang.Integer getRecordId() {
		return get("record_id");
	}

	/**
	 * 对应表的主键，如fund_id
	 */
	public void setOperationId(java.lang.Integer operationId) {
		set("operation_id", operationId);
	}

	/**
	 * 对应表的主键，如fund_id
	 */
	public java.lang.Integer getOperationId() {
		return get("operation_id");
	}

	/**
	 * 操作表
	 */
	public void setOperationTable(java.lang.String operationTable) {
		set("operation_table", operationTable);
	}

	/**
	 * 操作表
	 */
	public java.lang.String getOperationTable() {
		return get("operation_table");
	}

	/**
	 * 操作类型，增加、修改、删除
	 */
	public void setOperationType(java.lang.String operationType) {
		set("operation_type", operationType);
	}

	/**
	 * 操作类型，增加、修改、删除
	 */
	public java.lang.String getOperationType() {
		return get("operation_type");
	}

	/**
	 * 操作者
	 */
	public void setOperater(java.lang.String operater) {
		set("operater", operater);
	}

	/**
	 * 操作者
	 */
	public java.lang.String getOperater() {
		return get("operater");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
