package com.peseer.ops.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsOrgExtendEntity<M extends BaseOpsOrgExtendEntity<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_org_extend_entity";

	/**
	 * 自增Id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增Id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 
	 */
	public void setOrgCnShort(java.lang.String orgCnShort) {
		set("org_cn_short", orgCnShort);
	}

	/**
	 * 
	 */
	public java.lang.String getOrgCnShort() {
		return get("org_cn_short");
	}

	/**
	 * 
	 */
	public void setOrgPrimeEntity(java.lang.String orgPrimeEntity) {
		set("org_prime_entity", orgPrimeEntity);
	}

	/**
	 * 
	 */
	public java.lang.String getOrgPrimeEntity() {
		return get("org_prime_entity");
	}

	/**
	 * 
	 */
	public void setOrgEntity(java.lang.String orgEntity) {
		set("org_entity", orgEntity);
	}

	/**
	 * 
	 */
	public java.lang.String getOrgEntity() {
		return get("org_entity");
	}

	/**
	 * 对应org_entity的uuid
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 对应org_entity的uuid
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
