package com.peseer.ops.model.account.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginInfo<M extends BaseLoginInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "login_info";

	/**
	 * 
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 登录名
	 */
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	/**
	 * 登录名
	 */
	public java.lang.String getUid() {
		return get("uid");
	}

	/**
	 * 登录密码
	 */
	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	/**
	 * 登录密码
	 */
	public java.lang.String getPwd() {
		return get("pwd");
	}

	/**
	 * 登录cookie
	 */
	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}

	/**
	 * 登录cookie
	 */
	public java.lang.String getCookie() {
		return get("cookie");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
