package com.peseer.ops.model.account.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUdfRptCv<M extends BaseUdfRptCv<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "udf_rpt_cv";

	/**
	 * 
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 登录名
	 */
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	/**
	 * 登录名
	 */
	public java.lang.String getUid() {
		return get("uid");
	}

	/**
	 * 报告类型。可以参考ops_rdd.ops_report_cv的industry_id和industry_type字段
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 报告类型。可以参考ops_rdd.ops_report_cv的industry_id和industry_type字段
	 */
	public java.lang.Integer getType() {
		return get("type");
	}

	/**
	 * 报告周期：1-每月；2-每季度；3-每半年；4-每年
	 */
	public void setFrequency(java.lang.Integer frequency) {
		set("frequency", frequency);
	}

	/**
	 * 报告周期：1-每月；2-每季度；3-每半年；4-每年
	 */
	public java.lang.Integer getFrequency() {
		return get("frequency");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
