package com.peseer.ops.model.account.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUdfQa<M extends BaseUdfQa<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "udf_qa";

	/**
	 * 
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 登录名
	 */
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	/**
	 * 登录名
	 */
	public java.lang.String getUid() {
		return get("uid");
	}

	/**
	 * 事件详情 - 业务咨询描述
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	/**
	 * 事件详情 - 业务咨询描述
	 */
	public java.lang.String getContent() {
		return get("content");
	}

	/**
	 * 当前状态:1-未处理；2-审核中；3-审核无效；4-审核成功
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 当前状态:1-未处理；2-审核中；3-审核无效；4-审核成功
	 */
	public java.lang.Integer getStatus() {
		return get("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
