package com.peseer.ops.model.account.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "user_info";

	/**
	 * 登录名
	 */
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	/**
	 * 登录名
	 */
	public java.lang.String getUid() {
		return get("uid");
	}

	/**
	 * 登录类型:机构个人
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 登录类型:机构个人
	 */
	public java.lang.String getType() {
		return get("type");
	}

	/**
	 * 机构id
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构id
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 机构名称
	 */
	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	/**
	 * 机构名称
	 */
	public java.lang.String getOrgName() {
		return get("org_name");
	}

	/**
	 * 机构信息
	 */
	public void setOrgInfo(java.lang.String orgInfo) {
		set("org_info", orgInfo);
	}

	/**
	 * 机构信息
	 */
	public java.lang.String getOrgInfo() {
		return get("org_info");
	}

	/**
	 * 用户名真实姓名
	 */
	public void setCnName(java.lang.String cnName) {
		set("cn_name", cnName);
	}

	/**
	 * 用户名真实姓名
	 */
	public java.lang.String getCnName() {
		return get("cn_name");
	}

	/**
	 * 用户性别
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	/**
	 * 用户性别
	 */
	public java.lang.Integer getSex() {
		return get("sex");
	}

	/**
	 * 用户级别
	 */
	public void setLevel(java.lang.String level) {
		set("level", level);
	}

	/**
	 * 用户级别
	 */
	public java.lang.String getLevel() {
		return get("level");
	}

	/**
	 * 个人简介
	 */
	public void setPeopleInfo(java.lang.String peopleInfo) {
		set("people_info", peopleInfo);
	}

	/**
	 * 个人简介
	 */
	public java.lang.String getPeopleInfo() {
		return get("people_info");
	}

	/**
	 * 关注领域
	 */
	public void setDomainTips(java.lang.String domainTips) {
		set("domain_tips", domainTips);
	}

	/**
	 * 关注领域
	 */
	public java.lang.String getDomainTips() {
		return get("domain_tips");
	}

	/**
	 * 电话
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	/**
	 * 电话
	 */
	public java.lang.String getTelephone() {
		return get("telephone");
	}

	/**
	 * 邮箱
	 */
	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	/**
	 * 邮箱
	 */
	public java.lang.String getMail() {
		return get("mail");
	}

	/**
	 * 投资简介
	 */
	public void setVentureTips(java.lang.String ventureTips) {
		set("venture_tips", ventureTips);
	}

	/**
	 * 投资简介
	 */
	public java.lang.String getVentureTips() {
		return get("venture_tips");
	}

	/**
	 * 其他信息定制
	 */
	public void setOtherTips(java.lang.String otherTips) {
		set("other_tips", otherTips);
	}

	/**
	 * 其他信息定制
	 */
	public java.lang.String getOtherTips() {
		return get("other_tips");
	}

	/**
	 * 用户积分
	 */
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	/**
	 * 用户积分
	 */
	public java.lang.Integer getScore() {
		return get("score");
	}

	/**
	 * 上次登录时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	/**
	 * 上次登录时间
	 */
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
