package com.peseer.ops.model.online;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("daily_event_75", "id", DailyEvent75.class);

		arp.addMapping("event_round_one", "id", EventRoundOne.class);
		arp.addMapping("event_round_two", "id", EventRoundTwo.class);

		arp.addMapping("stat_dashboard", "id", StatDashboard.class);
		arp.addMapping("stat_event_round_one", "id", StatEventRoundOne.class);
		arp.addMapping("stat_event_round_two", "id", StatEventRoundTwo.class);
		arp.addMapping("rpt_stat_trend_all", "id", RptStatTrendAll.class);

	}
}

