package com.peseer.ops.model.account;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("login_info", "id", LoginInfo.class);
		arp.addMapping("udf_consult", "id", UdfConsult.class);
		arp.addMapping("udf_event", "id", UdfEvent.class);
		arp.addMapping("udf_monitor", "id", UdfMonitor.class);
		arp.addMapping("udf_qa", "id", UdfQa.class);
		arp.addMapping("udf_rpt_cv", "id", UdfRptCv.class);
		arp.addMapping("udf_rpt_trader", "id", UdfRptTrader.class);
		arp.addMapping("user_info", "uid", UserInfo.class);
	}
}

